---
# BuildConfig ConfigChange trigger does not actually trigger on configuration change!
- name: Start build
  command: oc start-build -n cakephp-build cakephp
  when:
  - current_build_version != ''
  - build_version != current_build_version
